stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GRADLE_USER_HOME: /cache/.gradle
  PIP_DOWNLOAD_CACHE: /cache/pip
  PIP_CACHE_DIR: /cache/pip-cache

junit:
  stage: test
  image: clovisai/wildfyre-java:latest # The image created in src/test/Dockerfile
  before_script:
    - ./api.sh
  script:
    - ./gradlew --no-daemon test
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml

static-analysis:
  stage: test
  image: clovisai/wildfyre-java:latest
  script:
    - ./gradlew --no-daemon findbugsMain findbugsTest
  artifacts:
    paths:
      - build/reports/findbugs/main.html
      - build/reports/findbugs/test.html

dokka:
  stage: test
  image: java:latest
  script:
    - ./gradlew --no-daemon dokka
  artifacts:
    paths:
      - build/docs/dokka
