stages:
  - test
  - documentation

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GRADLE_USER_HOME: /cache/.gradle
  PIP_DOWNLOAD_CACHE: /cache/pip

junit:
  stage: test
  image: clovisai/wildfyre-java:latest # The image created in src/test/Dockerfile
  before_script:
    - ./api.sh
  script:
    - ./gradlew test

static-analysis:
  stage: test
  image: clovisai/wildfyre-java:latest
  script:
    - ./gradlew findbugsMain findbugsTest

dokka:
  stage: documentation
  image: java:latest
  script:
    - ./gradlew dokka
