stages:
  - test
  - documentation

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - .gradle

junit:
  stage: test
  image: clovisai/java-python:latest # The image created in src/test/Dockerfile
  before_script:
    - ./api.sh
  script:
    - ./gradlew test
  cache:
    paths:
      - .gradle
      - .cache/pip/wheels

static-analysis:
  stage: test
  image: java:latest
  before_script:
    - BACK=$(pwd)
    - cd /usr/lib/jvm/java-8-openjdk-amd64
    - wget https://github.com/ensime/openjdk8src/blob/master/src.zip?raw=true
    - mv "src.zip?raw=true" src.zip
    - cd $BACK
  script:
    - ./gradlew findbugsMain findbugsTest

dokka:
  stage: documentation
  image: java:latest
  script:
    - ./gradlew dokka
