stages:
  - test
  - documentation

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - .gradle

junit:
  stage: test
  image: clovisai/java-python:latest # The image created in src/test/Dockerfile
  before_script:
    - lsof -i :8000
    - ./api.sh
  script:
    - ./gradlew test

static-analysis:
  stage: test
  image: java:latest
  script:
    - ./gradlew check

dokka:
  stage: documentation
  image: java:latest
  script:
    - ./gradlew dokka
