stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GRADLE_USER_HOME: /cache/.gradle
  PIP_DOWNLOAD_CACHE: /cache/pip
  PIP_CACHE_DIR: /cache/pip-cache

cache:
  paths:
    - .gradle
  key: v1

before_script:
  - ./gradlew --no-daemon clean 2> >(grep ZipFile && rm -rf /cache/.gradle/wrapper/dists/*)

junit:
  stage: test
  image: clovisai/wildfyre-java:latest # The image created in src/test/Dockerfile
  script:
    - ./api.sh
    - ./gradlew --no-daemon test
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    paths:
      - build/reports/tests/test

static-analysis:
  stage: test
  image: clovisai/wildfyre-java:latest
  script:
    - ./gradlew --no-daemon findbugsMain findbugsTest
  artifacts:
    paths:
      - build/reports/findbugs/main.html
      - build/reports/findbugs/test.html

dokka:
  stage: test
  image: java:latest
  script:
    - ./gradlew --no-daemon dokka
  artifacts:
    paths:
      - build/docs/dokka
